# Generated by Django 4.1.5 on 2023-01-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myblog',
            fields=[
                ('Name', models.CharField(max_length=40)),
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=40)),
                ('Description', models.TextField(default=' ')),
            ],
        ),
    ]
