# Generated by Django 4.1.5 on 2023-01-31 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myblog',
            old_name='Description',
            new_name='Content',
        ),
        migrations.RemoveField(
            model_name='myblog',
            name='Name',
        ),
        migrations.AddField(
            model_name='myblog',
            name='Author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myblog',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now()),
        ),
    ]
