# Generated by Django 4.1.5 on 2023-01-31 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_rename_description_myblog_content_remove_myblog_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myblog',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterField(
            model_name='myblog',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
